{% set name = "pagsanjan" %}
{% set version = "0.69" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: 0.69
  git_url: https://github.com/gcppineda/pagsanjan.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pandas

test:
  imports:
    - pandas
    - click

about:
  home: https://github.com/gcppineda/pagsanjan
  license: MIT
  license_family: MIT
  summary: For lean n' mean waterfall needs
